---
title: "r4ds_10"
author: "Vuk Dinic"
date: "2025-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 10 Exploratory data analysis

## 10.1 Introduction
### 10.1.1 Prerequisites
```{r}
library(tidyverse)
```
# 10.2 Questions
# 10.3 Variation
```{r}
ggplot(diamonds, aes(x = carat)) +
    geom_histogram(binwidth = 0.5) +
    theme_bw()
```
### 10.3.1 Typical values
```{r}
smaller <- diamonds %>% 
  filter(carat < 3)
```

```{r}
ggplot(smaller, aes(x = carat)) +
  geom_histogram(binwidth = 0.01)+
  theme_bw()
```

### 10.3.2 Unusual values
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram(binwidth = 0.5)
```
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram(binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 50))
```
```{r}
unusual <- diamonds %>% 
  filter(y < 3 | y > 20) %>% 
  select(price, x, y, z) %>% 
  arrange(y)
```

```{r}
unusual
```
### 10.3.3 Exercises
```{r}
ggplot(diamonds, aes(x = x)) +
  geom_histogram(binwidth = 0.5) +
  theme_bw()
```
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram(binwidth = 0.5) +
  theme_bw()
```
```{r}
ggplot(diamonds, aes(x = z)) +
  geom_histogram(binwidth = 0.5) +
  theme_bw()
```
```{r}
ggplot(diamonds, aes(x = price)) +
  geom_histogram(binwidth = 0.9) +
  theme_bw()
```
```{r}
diamonds
```
```{r}
one_carat <- diamonds %>% 
  filter(carat == 0.99 | carat == 1) %>% 
  select(carat, cut, price) %>% 
  arrange(carat)
```

```{r}
one_carat
```
```{r}
ggplot(one_carat, aes(x = carat)) +
  geom_bar()
```
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram() +
  coord_cartesian(ylim = c(0, 50))
```
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram(binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 50))
```
```{r}
ggplot(diamonds, aes(x = y)) +
  geom_histogram(binwidth = 0.5) +
  coord_cartesian(xlim = c(0, 50))
```
# 10.4 Unusual values
```{r}
diamonds2 <- diamonds %>% 
  filter(between(y, 3, 20))
```

```{r}
diamonds2 <- diamonds %>% 
  mutate(y = if_else(y < 3 | y > 20, NA, y))
```

```{r}
ggplot(diamonds2, aes(x = x, y = y)) +
  geom_point()
```
```{r}
ggplot(diamonds, aes(x = x, y = y)) +
  geom_point(na.rm = TRUE)
```
```{r}
nycflights13::flights %>% 
  mutate(
    canceled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + (sched_min / 60)
  ) %>%
  ggplot(aes(x = sched_dep_time)) + 
  geom_freqpoly(aes(color = canceled), binwidth = 1/4)
```
### 10.4.1 Exercises

```{r}
nycflights13::flights %>% 
  mutate(
    canceled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + (sched_min / 60)
  ) %>%
  ggplot(aes(x = sched_dep_time)) + 
  geom_freqpoly(aes(color = canceled), binwidth = 1/4)+
  facet_wrap(~canceled)
```
## 10.5 Covariaton
### 10.5.1 A categorical and a numerical variable

```{r}
ggplot(diamonds, aes(x = price)) +
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```

```{r}
ggplot(diamonds, aes(x = price, y = after_stat(density))) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```
```{r}
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_boxplot()
```

```{r}
ggplot(mpg, aes(x = class, y = hwy)) +
  geom_boxplot()
```
```{r}
ggplot(mpg, aes(x = fct_reorder(class, hwy, median), y = hwy)) +
  geom_boxplot()
```

```{r}
ggplot(mpg, aes(x = hwy, y = fct_reorder(class, hwy, median))) +
  geom_boxplot()
```

### 10.5.1.1 Exercises
```{r}
nycflights13::flights %>% 
  mutate(
    canceled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + (sched_min / 60)
  ) %>%
  ggplot(aes(x = sched_dep_time)) + 
  geom_freqpoly(aes(color = canceled), binwidth = 1/4)
```
```{r}
diamonds
```
```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point() +
  facet_wrap(~cut)
```
```{r}
ggplot(diamonds, aes(x = carat, y = cut)) +
  geom_point()
```
```{r}
ggplot(mpg, aes(x = fct_reorder(class, hwy, median), y = hwy)) +
  geom_boxplot() +
  coord_flip()
```
```{r}
library(lvplot)
```

```{r}
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_lv()
```
```{r}
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_violin()
```
```{r}
ggplot(diamonds, aes(x = price)) +
  geom_histogram() +
  facet_wrap(~cut)
```
```{r}
ggplot(diamonds, aes(x = price)) + 
  geom_freqpoly(aes(color = cut))
```
```{r}
ggplot(diamonds, aes(x = price)) +
  geom_density(aes(color = cut))
```
### 10.5.2 Two categorial variables
```{r}
ggplot(diamonds, aes(x = cut, y = color)) +
  geom_count()
```
```{r}
diamonds %>% 
  count(color, cut)
```
```{r}
diamonds %>% 
  count(color, cut) %>% 
  ggplot(aes(x = color, y = cut)) +
  geom_tile(aes(fill = n))
```
### 10.5.3 Two numerical variables
```{r}
ggplot(smaller, aes(x = carat, y = price)) +
  geom_point()
```
```{r}
ggplot(smaller, aes(x = carat, y = price)) +
  geom_point(alpha = 1 / 100)
```
```{r}
ggplot(smaller, aes(x = carat, y = price)) +
  geom_bin2d()
```
```{r}
ggplot(smaller, aes(x = carat, y = price)) +
  geom_hex()
```
```{r}
ggplot(smaller, aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1)))
```
### 10.5.3.1 Exercises
```{r}
ggplot(diamonds, aes(x = carat, y = price, color = cut_width(carat, width = 0.5))) +
  geom_point()
```
```{r}
ggplot(diamonds, aes(x = carat, y = price, color = cut_number(carat, n = 5))) +
  geom_point()
```
```{r}
ggplot(diamonds, aes(x = carat, fill = cut)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ cut) +
  theme_minimal()
```
```{r}
diamonds |> 
  filter(x >= 4) |> 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  coord_cartesian(xlim = c(4, 11), ylim = c(4, 11))
```
```{r}
ggplot(smaller, aes(x = carat, y = price)) + 
  geom_boxplot(aes(group = cut_number(carat, 20)))
```
## 10.6 Patterns and models
```{r}
library(tidymodels)
```

```{r}
diamonds <- diamonds |>
  mutate(
    log_price = log(price),
    log_carat = log(carat)
  )

diamonds_fit <- linear_reg() |>
  fit(log_price ~ log_carat, data = diamonds)

diamonds_aug <- augment(diamonds_fit, new_data = diamonds) |>
  mutate(.resid = exp(.resid))

ggplot(diamonds_aug, aes(x = carat, y = .resid)) + 
  geom_point()
```
```{r}
ggplot(diamonds_aug, aes(x = cut, y = .resid))+
  geom_boxplot()
```

