---
title: "r4ds_04"
author: "Vuk Dinic"
date: "2025-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workflow: code style
```{r}
library(tidyverse)
library(nycflights13)
```

## 4.1 Names
```{r}
short_flights <- flights %>% filter(air_time < 60)
```

## 4.2 Spaces
```{r}
# Strive for
#z <- (a + b)^2 / d

# Avoid
#z<-( a + b ) ^ 2/d
```

```{r}
# Strive for
#mean(x, na.rm = TRUE)

# Avoid
#mean (x ,na.rm=TRUE)
```

```{r}
flights %>%
  mutate(
    speed      = distance / air_time,
    dep_hour   = dep_time %/% 100,
    dep_minute = dep_time %%  100
  )
```


## 4.3 Pipes
```{r}
# Strive for
flights %>% 
  filter(!is.na(arr_delay), !is.na(tailnum)) %>% 
  count(dest)

```
```{r}
# Avoid
flights%>%filter(!is.na(arr_delay),!is.na(tailnum))%>%count(dest)
```
```{r}
# Strive for
flights %>% 
  group_by(tailnum) %>% 
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )
```
```{r}
# Avoid
flights %>% 
  group_by(
    tailnum
  ) %>% 
  summarize(delay = mean(arr_delay, na.rm = TRUE), n=n())
```
```{r}
# Strive for 
flights |>  
  group_by(tailnum) |> 
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )
```

```{r}
# Avoid
flights|>
  group_by(tailnum) |> 
  summarize(
             delay = mean(arr_delay, na.rm = TRUE), 
             n = n()
           )

```

## 4.4 ggplot2
```{r}
flights |> 
  group_by(month) |> 
  summarize(
    delay = mean(arr_delay, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = month, y = delay)) +
  geom_point() + 
  geom_line()
```
```{r}
flights |> 
  group_by(dest) |> 
  summarize(
    distance = mean(distance),
    speed = mean(distance / air_time, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = distance, y = speed)) +
  geom_smooth(
    method = "loess",
    span = 0.5,
    se = FALSE, 
    color = "white", 
    linewidth = 4
  ) +
  geom_point()
```

## 4.5 Sectioning comments
```{r}
# Load data --------------------------------------

# Plot data --------------------------------------
```
## 4.6 Exercises
```{r}
#Restyle the following pipelines
flights|>filter(dest=="IAH")|>group_by(year,month,day)|>summarize(n=n(),
delay=mean(arr_delay,na.rm=TRUE))|>filter(n>10)
```
```{r}
flights %>% 
  
  filter(dest == "IAH") %>% 
  
  group_by(year, month, day) %>% 
  
  summarize(n = n(),
            
delay =
  
  mean(arr_delay, na.rm = TRUE)) %>% 
  
  filter(n > 10)
```

```{r}
#Restyle the following pipelines
flights|>filter(carrier=="UA",dest%in%c("IAH","HOU"),sched_dep_time>
0900,sched_arr_time<2000)|>group_by(flight)|>summarize(delay=mean(
arr_delay,na.rm=TRUE),cancelled=sum(is.na(arr_delay)),n=n())|>filter(n>10)
```
```{r}
flights %>% 
  filter(
    carrier == "UA",
    dest%in%c("IAH", "HOU"),
    sched_dep_time > 0900,
    sched_arr_time < 2000) %>% 
  group_by(flight) %>% 
  summarize(
    delay = mean(arr_delay,na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n = n()) %>% 
  filter(n > 10)
```

